

    
##########################################
#
##########################################
def imagerepo():
    find("camsettings_btn_h4blacksettings.png") #camsettings_btn_h4blacksettings.png
    find("camsettings_btn_h4sessionsettings.png") #camsettings_btn_h4sessionsettings.png
    find("camsettings_btn_h4silversettings.png") #camsettings_btn_h4silversettings.png
    find("camsettings_img_h4black.png") #camsettings_img_h4black.png
    find("camsettings_img_h4session.png") #camsettings_img_h4session.png
    find("camsettings_img_h4silver.png") #camsettings_img_h4silver.png
    find("camsettings_txt_title.png") #camsettings_txt_title.png
    find("conncam_btn_getsupport.png") #conncam_btn_getsupport.png
    find("conncam_btn_gotit.png") #conncam_btn_gotit.png
    find("conncam_txt_camon.png") #conncam_txt_camon.png
    find("conncam_txt_plugcam.png") #conncam_txt_plugcam.png
    find("conncam_txt_selectimport.png") #conncam_txt_selectimport.png
    find("conncam_txt_title.png") #conncam_txt_title.png
    find("createacct_btn_getacct.png") #createacct_btn_getacct.png
    find("createacct_btn_signin.png") #createacct_btn_signin.png
    find("createacct_checked_getnews.png") #createacct_checked_getnews.png
    find("createacct_checked_iacknowledge.png") #createacct_checked_iacknowledge.png
    find("createacct_txt_subtitle.png") #createacct_txt_subtitle.png
    find("createacct_txt_title.png") #createacct_txt_title.png
    find("createacct_txtbox_email.png") #createacct_txtbox_email.png
    find("createacct_txtbox_password.png") #createacct_txtbox_password.png
    find("createacct_unchecked_getnews.png") #createacct_unchecked_getnews.png
    find("createacct_unchecked_iacknowledge.png") #createacct_unchecked_iacknowledge.png
    find("edits_btn_createedit.png") #edits_btn_createedit.png
    find("edits_img_edits.png") #edits_img_edits.png
    find("edits_txt_info.png") #edits_txt_info.png
    find("edits_txt_noedits.png") #edits_txt_noedits.png
    find("findmedia_btn_addfolder.png") #findmedia_btn_addfolder.png
    find("findmedia_btn_cancel.png") #findmedia_btn_cancel.png
    find("findmedia_btn_close.png") #findmedia_btn_close.png
    find("findmedia_btn_managefoldersettings.png") #findmedia_btn_managefoldersettings.png
    find("findmedia_btn_save.png") #findmedia_btn_save.png
    find("findmedia_txt_subtitle.png") #findmedia_txt_subtitle.png
    find("findmedia_txt_title.png") #findmedia_txt_title.png
    find("gensettings_btn_addnew.png") #gensettings_btn_addnew.png
    find("gensettings_btn_importlocation.png") #gensettings_btn_importlocation.png
    find("gensettings_btn_mediafoldersscan.png") #gensettings_btn_mediafoldersscan.png
    find("gensettings_selected_autodownload.png") #gensettings_selected_autodownload.png
    find("gensettings_selected_autolaunchapp.png") #gensettings_selected_autolaunchapp.png
    find("gensettings_selected_autoplay.png") #gensettings_selected_autoplay.png
    find("gensettings_selected_autosync.png") #gensettings_selected_autosync.png
    find("gensettings_txt_importlocation.png") #gensettings_txt_importlocation.png
    find("gensettings_txt_mediafolders.png") #gensettings_txt_mediafolders.png
    find("gensettings_txt_title.png") #gensettings_txt_title.png
    find("gensettings_unseleted_autodownload.png") #gensettings_unseleted_autodownload.png
    find("gensettings_unseleted_autolaunchapp.png") #gensettings_unseleted_autolaunchapp.png
    find("gensettings_unseleted_autoplay.png") #gensettings_unseleted_autoplay.png
    find("gensettings_unseleted_autosync.png") #gensettings_unseleted_autosync.png
    find("media_btn_choosefolder.png") #media_btn_choosefolder.png
    find("media_btn_connectcam.png") #media_btn_connectcam.png
    find("media_btn_settings.png") #media_btn_settings.png
    find("media_img_addmedia.png") #media_img_addmedia.png
    find("media_img_alerts.png") #media_img_alerts.png
    find("media_selected_edits.png") #media_selected_edits.png
    find("media_selected_hero4black.png") #media_selected_hero4black.png
    find("media_selected_hero4session.png") #media_selected_hero4session.png
    find("media_selected_hero4silver.png") #media_selected_hero4silver.png
    find("media_selected_media.png") #media_selected_media.png
    find("media_selected_recentlyadd.png") #media_selected_recentlyadd.png
    find("media_txt_title.png") #media_txt_title.png
    find("media_unselected_edits.png") #media_unselected_edits.png
    find("media_unselected_hero4black.png") #media_unselected_hero4black.png
    find("media_unselected_hero4session.png") #media_unselected_hero4session.png
    find("media_unselected_hero4silver.png") #media_unselected_hero4silver.png
    find("media_unselected_media.png") #media_unselected_media.png
    find("media_unselected_recentlyadd.png") #media_unselected_recentlyadd.png
    find("mediacam_btn_importfiles.png") #mediacam_btn_importfiles.png
    find("mediacam_txt_spaceused.png") #mediacam_txt_spaceused.png
    find("mediacamsettings_btn_cancel.png") #mediacamsettings_btn_cancel.png
    find("mediacamsettings_btn_close.png") #mediacamsettings_btn_close.png
    find("mediacamsettings_btn_save.png") #mediacamsettings_btn_save.png
    find("mediacamsettings_checked_autodelete.png") #mediacamsettings_checked_autodelete.png
    find("mediacamsettings_checked_autoimport.png") #mediacamsettings_checked_autoimport.png
    find("mediacamsettings_unchecked_autodelete.png") #mediacamsettings_unchecked_autodelete.png
    find("mediacamsettings_unchecked_autoimport.png") #mediacamsettings_unchecked_autoimport.png
    find("mediah4black_img_logo.png") #mediah4black_img_logo.png
    find("mediah4black_txt_available.png") #mediah4black_txt_available.png
    find("mediah4black_txt_capacity.png") #mediah4black_txt_capacity.png
    find("mediah4black_txt_subtitle.png") #mediah4black_txt_subtitle.png
    find("mediah4black_txt_title.png") #mediah4black_txt_title.png
    find("mediah4black_txt_used.png") #mediah4black_txt_used.png
    find("mediah4session_img_logo.png") #mediah4session_img_logo.png
    find("mediah4session_txt_available.png") #mediah4session_txt_available.png
    find("mediah4session_txt_capacity.png") #mediah4session_txt_capacity.png
    find("mediah4session_txt_subtitle.png") #mediah4session_txt_subtitle.png
    find("mediah4session_txt_title.png") #mediah4session_txt_title.png
    find("mediah4session_txt_used.png") #mediah4session_txt_used.png
    find("mediah4silver_img_logo.png") #mediah4silver_img_logo.png
    find("mediah4silver_txt_available.png") #mediah4silver_txt_available.png
    find("mediah4silver_txt_capacity.png") #mediah4silver_txt_capacity.png
    find("mediah4silver_txt_subtitle.png") #mediah4silver_txt_subtitle.png
    find("mediah4silver_txt_title.png") #mediah4silver_txt_title.png
    find("mediah4silver_txt_used.png") #mediah4silver_txt_used.png
    find("mediasettingsh4black_txt_cammodel.png") #mediasettingsh4black_txt_cammodel.png
    find("mediasettingsh4black_txtbox_camfolder.png") #mediasettingsh4black_txtbox_camfolder.png
    find("mediasettingsh4session_txt_cammodel.png") #mediasettingsh4session_txt_cammodel.png
    find("mediasettingsh4session_txtbox_camfolder.png") #mediasettingsh4session_txtbox_camfolder.png
    find("mediasettingsh4silver_txt_cammodel.png") #mediasettingsh4silver_txt_cammodel.png
    find("mediasettingsh4silver_txtbox_camfolder.png") #mediasettingsh4silver_txtbox_camfolder.png
    find("popup_btn_indexinfo.png") #popup_btn_indexinfo.png
    find("recentlyadd_btn_addmedia.png") #recentlyadd_btn_addmedia.png
    find("recentlyadd_btn_connectcam.png") #recentlyadd_btn_connectcam.png
    find("recentlyadd_txt_title.png") #recentlyadd_txt_title.png
    find("settings_btn_backtomedia.png") #settings_btn_backtomedia.png
    find("settings_selected_camsettings.png") #settings_selected_camsettings.png
    find("settings_selected_gensettings.png") #settings_selected_gensettings.png
    find("settings_unselected_camsettings.png") #settings_unselected_camsettings.png
    find("settings_unselected_gensettings.png") #settings_unselected_gensettings.png
    find("signin_btn_forgot.png") #signin_btn_forgot.png
    find("signin_btn_needacct.png") #signin_btn_needacct.png
    find("signin_btn_resendemail.png") #signin_btn_resendemail.png
    find("signin_btn_signin.png") #signin_btn_signin.png
    find("signin_img_logo.png") #signin_img_logo.png
    find("signin_txt_title.png") #signin_txt_title.png
    find("signin_txtbox_emailpw.png") #signin_txtbox_emailpw.png
    find("startup_btn_continue.png") #startup_btn_continue.png
    find("startup_checked_autolaunchcam.png") #startup_checked_autolaunchcam.png
    find("startup_img_camhappy.png") #startup_img_camhappy.png
    find("startup_img_findmoments.png") #startup_img_findmoments.png
    find("startup_img_importmedia.png") #startup_img_importmedia.png
    find("startup_img_logo.png") #startup_img_logo.png
    find("startup_txt_title.png") #startup_txt_title.png
    find("startup_unchecked_autolaunchcam.png") #startup_unchecked_autolaunchcam.png
    find("user_btn_select.png") #user_btn_select.png
    find("user_btn_signoff.png") #user_btn_signoff.png
